# Generated by Django 5.2.16 on 2026-08-04 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0019_booking_flight_number'),
        ('fleet', '0009_vehiclephoto_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_pings', to='bookings.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_pings', to='fleet.driver')),
            ],
            options={
                'indexes': [models.Index(fields=['booking', 'recorded_at'], name='tracking_po_booking_139089_idx')],
            },
        ),
    ]
