# Generated by Django 5.2.16 on 2026-07-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fleet', '0002_seed_default_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Procentowy'), ('FIXED', 'Kwotowy')], default='PERCENT', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Dla typu procentowego: liczba 0-100. Dla kwotowego: złotówki.', max_digits=6)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Puste = bez limitu.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance_km', models.PositiveSmallIntegerField(help_text='Górna granica tej taryfy (km rzeczywistej trasy).', unique=True)),
                ('price_reserved', models.DecimalField(decimal_places=2, help_text='Cena przy rezerwacji z wyprzedzeniem (patrz ADVANCE_BOOKING_THRESHOLD_HOURS).', max_digits=7)),
                ('price_on_demand', models.DecimalField(decimal_places=2, help_text='Cena przy zamówieniu na już / bez wcześniejszej rezerwacji.', max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Taryfa odległościowa',
                'verbose_name_plural': 'Taryfy odległościowe',
                'ordering': ['max_distance_km'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=200)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_address', models.CharField(max_length=200)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('NOWA', 'Nowa (oczekuje na potwierdzenie)'), ('POTWIERDZONA', 'Potwierdzona'), ('KIEROWCA_W_DRODZE', 'Kierowca w drodze'), ('W_TRAKCIE', 'W trakcie kursu'), ('ZAKONCZONA', 'Zakończona'), ('ANULOWANA', 'Anulowana')], default='NOWA', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, help_text='Rzeczywista odległość trasy (OSRM), zapisana w momencie rezerwacji.', max_digits=6, null=True)),
                ('is_reserved', models.BooleanField(default=True, help_text='Czy zamówiono z wyprzedzeniem (cena rezerwacji) czy na już (cena bez rezerwacji).')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Cena z dopasowanej taryfy (po rabacie kuponu). Puste = wycena indywidualna.', max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='fleet.driver')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.customer')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.coupon')),
                ('pricing_tier', models.ForeignKey(blank=True, help_text='Taryfa dopasowana wg dystansu w momencie rezerwacji.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.pricingtier')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
