# Generated by Django 5.2.16 on 2026-07-28 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_pricing_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Liczba osób — pomaga zdecydować, czy wysłać bus czy auto osobowe.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
