# Generated by Django 5.2.16 on 2026-07-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_passenger_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-scheduled_at'], 'verbose_name': 'Rezerwacja', 'verbose_name_plural': 'Rezerwacje'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Kupon rabatowy', 'verbose_name_plural': 'Kupony rabatowe'},
        ),
    ]
