# Generated by Django 5.2.16 on 2026-07-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_options_alter_coupon_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFarePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximity_threshold_km', models.DecimalField(decimal_places=1, default=10.0, help_text='Jeśli najbliższy znany kierowca (wolny, albo kończący bieżący kurs) jest bliżej niż X km od miejsca odbioru, stosujemy taryfę lokalną zamiast cennika.', max_digits=5)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Taryfa lokalna',
                'verbose_name_plural': 'Taryfa lokalna',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='pricing_mode',
            field=models.CharField(choices=[('tier', 'Cennik odległościowy'), ('local', 'Taryfa lokalna')], default='tier', help_text='Jak wyliczono cenę: cennik odległościowy czy taryfa lokalna (bliski kierowca).', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pricing_tier',
            field=models.ForeignKey(blank=True, help_text='Taryfa dopasowana wg dystansu w momencie rezerwacji (puste przy taryfie lokalnej).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.pricingtier'),
        ),
    ]
