# Generated by Django 5.2.16 on 2026-07-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_seed_local_fare_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='site',
            field=models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', help_text='Z której marki przyszła ta rezerwacja — decyduje m.in. o brandingu SMS-a do klienta.', max_length=20),
        ),
    ]
