# Generated by Django 5.2.16 on 2026-07-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20, unique=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=50, help_text='Zaliczka wymagana do zablokowania terminu po potwierdzeniu rezerwacji.', max_digits=7)),
                ('payment_window_minutes', models.PositiveSmallIntegerField(default=60, help_text='Ile minut klient ma na zapłatę zaliczki po potwierdzeniu, zanim rezerwacja wygaśnie.')),
                ('driver_buffer_minutes', models.PositiveSmallIntegerField(default=60, help_text='Minimalny odstęp (w obie strony) między godzinami dwóch potwierdzonych kursów — czas na powrót kierowcy do bazy. Nowe rezerwacje w tym oknie są odrzucane.')),
                ('dispatcher_phone', models.CharField(blank=True, help_text='Numer, na który idzie SMS o nowej rezerwacji do potwierdzenia.', max_length=16)),
                ('dispatcher_email', models.EmailField(blank=True, help_text='Adres, na który idzie e-mail o nowej rezerwacji do potwierdzenia.', max_length=254)),
            ],
            options={
                'verbose_name': 'Ustawienia rezerwacji',
                'verbose_name_plural': 'Ustawienia rezerwacji',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zaliczka do zapłaty — zrzut z ustawień w momencie potwierdzenia rezerwacji.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Ustawiane przy potwierdzeniu — po tym czasie niezapłacona rezerwacja jest automatycznie anulowana.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('NOWA', 'Nowa (oczekuje na potwierdzenie)'), ('POTWIERDZONA', 'Potwierdzona (oczekuje na zaliczkę)'), ('OPLACONA', 'Opłacona (oczekuje na kierowcę)'), ('KIEROWCA_W_DRODZE', 'Kierowca w drodze'), ('W_TRAKCIE', 'W trakcie kursu'), ('ZAKONCZONA', 'Zakończona'), ('ANULOWANA', 'Anulowana')], default='NOWA', max_length=20),
        ),
    ]
