# Generated by Django 5.2.16 on 2026-08-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_seed_dispatcher_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='booking',
            name='tracking_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
