# Generated by Django 5.2.16 on 2026-08-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_tracking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_code_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
