# Generated by Django 5.2.16 on 2026-08-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_tracking_code_valid_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DEPOSIT', 'Zaliczka'), ('REMAINDER', 'Dopłata')], default='DEPOSIT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stripe_payment_intent_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('SUCCEEDED', 'Opłacone'), ('FAILED', 'Nieudane')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Płatność',
                'verbose_name_plural': 'Płatności',
                'ordering': ['-created_at'],
            },
        ),
    ]
