# Generated by Django 5.2.16 on 2026-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='bookings_paused',
            field=models.BooleanField(default=False, help_text="Wyłącza formularz rezerwacji na stronie (np. na czas urlopu). Niezależne od statusu kierowców — kurs można zarezerwować z wyprzedzeniem nawet gdy żaden kierowca akurat nie jest 'Aktywny (wolny)'."),
        ),
    ]
