# Generated by Django 5.2.16 on 2026-08-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_bookingsettings_bookings_paused'),
        ('content', '0031_seed_regulamin_pages'),
        ('fleet', '0009_vehiclephoto_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fixed_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.fixedroute'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.tour'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
    ]
