# Generated by Django 5.2.16 on 2026-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_fixed_route_booking_tour_booking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ile minut ten kurs zajmuje kierowcy w obie strony — zrzut z FixedRoute/Tour.duration_minutes w momencie rezerwacji (katalogowe rezerwacje transfer247.pl). Puste = używany jest domyślny bufor z Ustawień rezerwacji (has_conflicting_booking w apps.bookings.availability).', null=True),
        ),
    ]
