# Generated by Django 5.2.16 on 2026-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remainder_paid_at',
            field=models.DateTimeField(blank=True, help_text='Kiedy reszta należności (price - deposit_amount) wpłynęła — ustawiane też razem z paid_at przy płatności całej kwoty od razu. Kurs jest opłacony w całości dokładnie wtedy, gdy to pole nie jest puste.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Kiedy zaliczka (lub pełna kwota) wpłynęła.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('DEPOSIT', 'Zaliczka'), ('REMAINDER', 'Dopłata'), ('FULL', 'Pełna kwota')], default='DEPOSIT', max_length=10),
        ),
    ]
