# Generated by Django 5.2.16 on 2026-08-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_booking_completed_at_booking_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(blank=True, help_text='Opcjonalny numer lotu (transfery lotniskowe) — pozwala dyspozytorowi sprawdzić opóźnienia.', max_length=20),
        ),
    ]
