# Generated by Django 5.2.16 on 2026-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Migawka FixedRouteVehiclePrice/TourVehiclePrice.price_eur w momencie rezerwacji — tylko dla rezerwacji z katalogu transfer247.pl. Puste = płatność w EUR niedostępna dla tego kursu (price zostaje jedynym źródłem prawdy o cenie; price_eur tylko odblokowuje płatność w EUR).', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('pln', 'PLN'), ('eur', 'EUR')], default='pln', max_length=3),
        ),
    ]
