# Generated by Django 5.2.16 on 2026-08-06 08:07

from django.db import migrations, models


def _bump_minimum_fare_to_49(apps, schema_editor):
    # An existing (pre-refactor) LocalFarePolicy row keeps whatever
    # minimum_fare it had (e.g. 40.00) — the new field defaults only apply
    # to rows created from here on, so the live singleton needs an explicit
    # nudge to the confirmed 49 zł base fare.
    LocalFarePolicy = apps.get_model("bookings", "LocalFarePolicy")
    LocalFarePolicy.objects.filter(minimum_fare=40).update(minimum_fare=49)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_child_seat_ages_booking_bike_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfarepolicy',
            name='included_km',
            field=models.PositiveSmallIntegerField(default=10, help_text='Ile km trasy pokrywa stawka minimalna, zanim naliczy się cena za km.'),
        ),
        migrations.AddField(
            model_name='localfarepolicy',
            name='local_max_distance_km',
            field=models.PositiveSmallIntegerField(default=20, help_text='Powyżej ilu km trasy taryfa lokalna przestaje obowiązywać (dalej liczymy z cennika strefowego).'),
        ),
        migrations.AlterField(
            model_name='localfarepolicy',
            name='minimum_fare',
            field=models.DecimalField(decimal_places=2, default=49.0, help_text='Stawka za pierwsze included_km trasy.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='localfarepolicy',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Cena za każdy km powyżej included_km.', max_digits=5),
        ),
        migrations.RunPython(_bump_minimum_fare_to_49, migrations.RunPython.noop),
    ]
