# Generated by Django 5.2.16 on 2026-09-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_localfarepolicy_included_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='language',
            field=models.CharField(choices=[('pl', 'Polski'), ('en', 'English'), ('de', 'Deutsch')], default='pl', help_text='Język, w którym klient korzystał ze strony przy rezerwacji — w tym języku dostaje SMS-y i e-maile (kod, potwierdzenie, kierowca w drodze, zmiana terminu, anulowanie). Powiadomienia dla dyspozytora i kierowców zawsze po polsku.', max_length=2),
        ),
    ]
