# Generated by Django 5.2.16 on 2026-09-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_booking_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay_token',
            field=models.CharField(blank=True, editable=False, help_text='Losowy token w krótkim linku do płatności (/pay/<token>) z SMS-a — bez logowania.', max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_currency',
            field=models.CharField(choices=[('pln', 'PLN'), ('eur', 'EUR')], default='pln', help_text='Waluta, w której klient płaci zaliczkę i resztę (link SMS). Ustawiana automatycznie: klient w języku innym niż polski płaci w EUR. Możesz to zmienić ręcznie przed wysłaniem linku.', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_link_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Kiedy ostatnio wysłano klientowi SMS-em link do płatności.', null=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='eur_exchange_rate',
            field=models.DecimalField(decimal_places=4, default='4.3000', help_text='Ile PLN za 1 EUR — do przeliczenia zaliczki/reszty dla klientów płacących w EUR, gdy kurs nie ma własnej ceny w EUR (np. rezerwacje z mapy na dowieziemycie.pl). Kursy katalogowe transfer247.pl liczą EUR ze swojej ceny w EUR.', max_digits=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Sesja Stripe Checkout, jeśli to płatność z linku wysłanego SMS-em.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
