# Generated by Django 5.2.16 on 2026-09-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_payment_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Do kiedy klient ma zapłacić zaliczkę (ustawiane przy potwierdzeniu, ale możesz je ręcznie zmienić). Po tym czasie niezapłacona rezerwacja jest automatycznie anulowana (cron co 5 min), a link do płatności przestaje działać.', null=True, verbose_name='Czas na zapłatę zaliczki'),
        ),
    ]
