# Generated by Django 5.2.16 on 2026-09-21 09:01

from django.db import migrations, models


def raise_old_default_deposit(apps, schema_editor):
    """The flat default deposit was 50 zł; the new rule is 100 zł (capped at
    50% of the ride price). Only rows still on the old default are touched — a
    value someone set on purpose stays."""
    apps.get_model("bookings", "BookingSettings").objects.filter(deposit_amount=50).update(deposit_amount=100)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_payment_deadline_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zaliczka do zapłaty w euro (klient w innym języku niż polski). Puste = domyślna z Ustawień rezerwacji (np. 25 EUR, nie więcej niż 50% ceny w EUR, do pełnych euro).', max_digits=7, null=True, verbose_name='Zaliczka w EUR'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='deposit_amount_eur',
            field=models.DecimalField(decimal_places=2, default=25, help_text='Domyślna zaliczka w EUR (dla klientów w języku innym niż polski), gdy rezerwacja nie ma własnej. Nie więcej niż podany niżej procent ceny kursu; zaokrąglana do pełnych euro.', max_digits=7),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='deposit_max_percent',
            field=models.PositiveSmallIntegerField(default=50, help_text='Domyślna zaliczka nie przekroczy tego procentu ceny kursu (np. 50 = połowa).'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zaliczka do zapłaty w złotówkach (klient w języku polskim). Ustaw ją przed potwierdzeniem albo zostaw puste — wtedy przy potwierdzeniu wyliczy się domyślna z Ustawień rezerwacji (np. 100 zł, nie więcej niż 50% ceny, do pełnych złotych).', max_digits=7, null=True, verbose_name='Zaliczka w PLN'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Domyślna zaliczka w PLN (dla klientów płacących w złotówkach), gdy rezerwacja nie ma własnej. Nie więcej niż podany niżej procent ceny kursu; zaokrąglana do pełnych złotych.', max_digits=7),
        ),
        migrations.RunPython(raise_old_default_deposit, migrations.RunPython.noop),
    ]
