# Generated by Django 5.2.16 on 2026-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_deposit_in_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remainder_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kwota ustalona ręcznie do zapłaty po zaliczce (np. po targach albo gdy cena wzrosła w trakcie kursu). Puste = cena kursu minus zaliczka. Używana przez link do dopłaty.', max_digits=7, null=True, verbose_name='Do zapłaty na koniec — PLN'),
        ),
        migrations.AddField(
            model_name='booking',
            name='remainder_amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='To samo w euro (klient płacący w EUR). Puste = cena w EUR minus zaliczka w EUR.', max_digits=7, null=True, verbose_name='Do zapłaty na koniec — EUR'),
        ),
    ]
