# Generated by Django 5.2.16 on 2026-07-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('page_type', models.CharField(choices=[('TRANSFER_LOTNISKO', 'Transfer lotniskowy'), ('NOCNY_TRANSFER', 'Nocny transfer'), ('CENNIK', 'Cennik'), ('O_NAS', 'O nas'), ('KONTAKT', 'Kontakt'), ('BLOG', 'Wpis blogowy'), ('INNE', 'Inne')], default='INNE', max_length=24)),
                ('title_pl', models.CharField(max_length=160)),
                ('title_en', models.CharField(max_length=160)),
                ('body_pl', models.TextField(blank=True, help_text='Treść strony (Markdown).')),
                ('body_en', models.TextField(blank=True)),
                ('seo_title_pl', models.CharField(blank=True, max_length=160)),
                ('seo_title_en', models.CharField(blank=True, max_length=160)),
                ('seo_description_pl', models.CharField(blank=True, max_length=320)),
                ('seo_description_en', models.CharField(blank=True, max_length=320)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title_pl'],
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_pl', models.CharField(max_length=160)),
                ('eyebrow_en', models.CharField(max_length=160)),
                ('headline_pl', models.CharField(help_text='Użyj {highlight} tam, gdzie ma się pojawić wyróżnione słowo.', max_length=160)),
                ('headline_en', models.CharField(help_text='Use {highlight} where the accent word should appear.', max_length=160)),
                ('headline_highlight_pl', models.CharField(max_length=40)),
                ('headline_highlight_en', models.CharField(max_length=40)),
                ('lead_pl', models.TextField()),
                ('lead_en', models.TextField()),
                ('footnote_pl', models.CharField(max_length=200)),
                ('footnote_en', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Treść strony głównej',
                'verbose_name_plural': 'Treść strony głównej',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pl', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('summary_pl', models.CharField(blank=True, help_text='Krótki opis pod kartę na liście.', max_length=240)),
                ('summary_en', models.CharField(blank=True, max_length=240)),
                ('body_pl', models.TextField(blank=True, help_text='Treść strony (Markdown).')),
                ('body_en', models.TextField(blank=True)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tours/covers/')),
                ('seo_title_pl', models.CharField(blank=True, max_length=160)),
                ('seo_title_en', models.CharField(blank=True, max_length=160)),
                ('seo_description_pl', models.CharField(blank=True, max_length=320)),
                ('seo_description_en', models.CharField(blank=True, max_length=320)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title_pl'],
            },
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.tour')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
