# Generated by Django 5.2.16 on 2026-07-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_seed_home_and_tours'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('destination_town', models.CharField(max_length=80)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('title_pl', models.CharField(max_length=160)),
                ('title_en', models.CharField(max_length=160)),
                ('lead_pl', models.TextField(help_text='Krótki wstęp pod nagłówkiem.')),
                ('lead_en', models.TextField()),
                ('body_pl', models.TextField(blank=True, help_text='Dłuższa treść SEO (Markdown).')),
                ('body_en', models.TextField(blank=True)),
                ('seo_title_pl', models.CharField(blank=True, max_length=160)),
                ('seo_title_en', models.CharField(blank=True, max_length=160)),
                ('seo_description_pl', models.CharField(blank=True, max_length=320)),
                ('seo_description_en', models.CharField(blank=True, max_length=320)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trasa lokalna',
                'verbose_name_plural': 'Trasy lokalne',
                'ordering': ['order', 'destination_town'],
            },
        ),
    ]
