# Generated by Django 5.2.16 on 2026-07-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_seed_local_routes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpage',
            options={'ordering': ['title_pl'], 'verbose_name': 'Strona treści', 'verbose_name_plural': 'Strony treści'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['order', 'title_pl'], 'verbose_name': 'Wycieczka', 'verbose_name_plural': 'Wycieczki'},
        ),
        migrations.AlterModelOptions(
            name='tourphoto',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Zdjęcie wycieczki', 'verbose_name_plural': 'Zdjęcia wycieczki'},
        ),
    ]
