# Generated by Django 5.2.16 on 2026-07-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_fix_home_content_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('tag_pl', models.CharField(blank=True, help_text='Np. „Poradnik”, „Lotnisko”.', max_length=60)),
                ('tag_en', models.CharField(blank=True, max_length=60)),
                ('tag_de', models.CharField(blank=True, max_length=60)),
                ('title_pl', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_de', models.CharField(blank=True, max_length=200)),
                ('excerpt_pl', models.CharField(blank=True, max_length=320)),
                ('excerpt_en', models.CharField(blank=True, max_length=320)),
                ('excerpt_de', models.CharField(blank=True, max_length=320)),
                ('body_pl', models.TextField(blank=True, help_text='Treść artykułu (Markdown).')),
                ('body_en', models.TextField(blank=True)),
                ('body_de', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('seo_title_pl', models.CharField(blank=True, max_length=160)),
                ('seo_title_en', models.CharField(blank=True, max_length=160)),
                ('seo_title_de', models.CharField(blank=True, max_length=160)),
                ('seo_description_pl', models.CharField(blank=True, max_length=320)),
                ('seo_description_en', models.CharField(blank=True, max_length=320)),
                ('seo_description_de', models.CharField(blank=True, max_length=320)),
                ('published_at', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wpis bloga',
                'verbose_name_plural': 'Wpisy bloga',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='FixedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='transfer247', max_length=20)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name_pl', models.CharField(max_length=160)),
                ('name_en', models.CharField(max_length=160)),
                ('name_de', models.CharField(blank=True, max_length=160)),
                ('duration', models.CharField(blank=True, help_text='Np. „~25 min” — tekst dowolny.', max_length=40)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_large_vehicle', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('body_pl', models.TextField(blank=True, help_text='Treść strony (Markdown) — wstęp, sekcje, FAQ.')),
                ('body_en', models.TextField(blank=True)),
                ('body_de', models.TextField(blank=True)),
                ('seo_title_pl', models.CharField(blank=True, max_length=160)),
                ('seo_title_en', models.CharField(blank=True, max_length=160)),
                ('seo_title_de', models.CharField(blank=True, max_length=160)),
                ('seo_description_pl', models.CharField(blank=True, max_length=320)),
                ('seo_description_en', models.CharField(blank=True, max_length=320)),
                ('seo_description_de', models.CharField(blank=True, max_length=320)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trasa stała (transfer247)',
                'verbose_name_plural': 'Trasy stałe (transfer247)',
                'ordering': ['order', 'name_pl'],
            },
        ),
        migrations.AddField(
            model_name='contentpage',
            name='site',
            field=models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='eyebrow_de',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='footnote_de',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='headline_de',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='headline_highlight_de',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='lead_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='site',
            field=models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='body_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, help_text='Np. „do 6 h” — tekst dowolny.', max_length=40),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_large_vehicle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena drugim/większym pojazdem, jeśli dotyczy (np. Ford Tourneo Custom u transfer247).', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='seo_description_de',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='tour',
            name='seo_title_de',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='tour',
            name='site',
            field=models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='summary_de',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_de',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='eyebrow_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='eyebrow_pl',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='footnote_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='footnote_pl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='headline_highlight_en',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='headline_highlight_pl',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='tour',
            name='body_pl',
            field=models.TextField(blank=True, help_text='Treść strony (Markdown) — wstęp, sekcje, FAQ.'),
        ),
    ]
