# Generated by Django 5.2.16 on 2026-07-30 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_seed_transfer247'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(help_text='Np. „Toyota Auris Hybrid” — nazwa własna, bez tłumaczenia.', max_length=80)),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('description_pl', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='fleet-showcase/covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pojazd (prezentacja floty)',
                'verbose_name_plural': 'Flota (prezentacja)',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FleetVehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fleet-showcase/gallery/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.fleetvehicle')),
            ],
            options={
                'verbose_name': 'Zdjęcie pojazdu (flota)',
                'verbose_name_plural': 'Zdjęcia pojazdu (flota)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
