# Generated by Django 5.2.16 on 2026-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_seed_transfer247_contact_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedroute',
            name='h1_de',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fixedroute',
            name='h1_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fixedroute',
            name='h1_pl',
            field=models.CharField(blank=True, help_text='Nagłówek H1 na podstronie — dłuższa, pełna fraza kluczowa (np. „Transfer z lotniska Kraków-Balice do centrum miasta”). Puste pole = użyty zostanie name_pl.', max_length=200),
        ),
        migrations.AddField(
            model_name='tour',
            name='h1_de',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tour',
            name='h1_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tour',
            name='h1_pl',
            field=models.CharField(blank=True, help_text='Nagłówek H1 na podstronie — dłuższa, pełna fraza kluczowa (np. „Wycieczka do Auschwitz-Birkenau z Krakowa”). Puste pole = użyty zostanie title_pl.', max_length=200),
        ),
        migrations.AlterField(
            model_name='fixedroute',
            name='name_pl',
            field=models.CharField(help_text='Krótka nazwa — używana w menu, na kartach, w stopce.', max_length=160),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title_pl',
            field=models.CharField(help_text='Krótki tytuł — używany w menu, na kartach, w stopce.', max_length=120),
        ),
    ]
