# Generated by Django 5.2.16 on 2026-07-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_fix_auris_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetvehiclephoto',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='fixedroute',
            name='price_from_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena w euro dla wersji EN/DE strony — wpisywana ręcznie, nie przeliczana automatycznie.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fixedroute',
            name='price_large_vehicle_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_from_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena w euro dla wersji EN/DE strony — wpisywana ręcznie, nie przeliczana automatycznie.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_large_vehicle_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='FleetVehicle',
        ),
        migrations.DeleteModel(
            name='FleetVehiclePhoto',
        ),
    ]
