# Generated by Django 5.2.16 on 2026-08-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_contentpage_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedroute',
            name='category',
            field=models.CharField(choices=[('LOTNISKO', 'Transfer lotniskowy'), ('DWORZEC_PKP', 'Transfer z dworca PKP')], default='LOTNISKO', help_text='Decyduje w którym dziale menu (i sekcji na /transfery) trasa się pojawia.', max_length=20),
        ),
    ]
