# Generated by Django 5.2.16 on 2026-08-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_transfer247_rough_eur_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='page_type',
            field=models.CharField(choices=[('TRANSFER_LOTNISKO', 'Transfer lotniskowy'), ('NOCNY_TRANSFER', 'Nocny transfer'), ('CENNIK', 'Cennik'), ('O_NAS', 'O nas'), ('KONTAKT', 'Kontakt'), ('BLOG', 'Wpis blogowy'), ('TRANSPORT_ROWEROW', 'Transport rowerów'), ('REGULAMIN', 'Regulamin'), ('INNE', 'Inne')], default='INNE', max_length=24),
        ),
    ]
