# Generated by Django 5.2.16 on 2026-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_seed_regulamin_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedroute',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ile minut zajmuje kierowcy cały kurs w obie strony (dojazd na miejsce + powrót). Blokuje ten czas w harmonogramie, żeby nikt inny nie mógł zarezerwować kursu, gdy kierowca jeszcze nie wrócił. Puste = używany jest domyślny bufor z Ustawień rezerwacji.', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ile minut zajmuje kierowcy cała wycieczka w obie strony (dojazd + czas na miejscu + powrót). Blokuje ten czas w harmonogramie, żeby nikt inny nie mógł zarezerwować kursu, gdy kierowca jeszcze nie wrócił. Puste = używany jest domyślny bufor z Ustawień rezerwacji.', null=True),
        ),
    ]
