# Generated by Django 5.2.16 on 2026-08-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_fixedroute_duration_minutes_tour_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Pełny link do filmu YouTube (np. https://www.youtube.com/watch?v=...) — osadzany pod treścią artykułu. Puste = brak filmu.'),
        ),
        migrations.CreateModel(
            name='BlogPostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_pl', models.CharField(help_text='Np. „Kup bilety online”, „Strona muzeum”.', max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('label_de', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.blogpost')),
            ],
            options={
                'verbose_name': 'Link powiązany',
                'verbose_name_plural': 'Linki powiązane',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/gallery/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='blog/gallery/thumbs/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.blogpost')),
            ],
            options={
                'verbose_name': 'Zdjęcie artykułu',
                'verbose_name_plural': 'Galeria artykułu',
                'ordering': ['order', 'id'],
            },
        ),
    ]
