# Generated by Django 5.2.16 on 2026-08-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_seed_imprezy_wynajem_cennik_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Kolejność na liście /imprezy — mniejsze wyżej.')),
                ('icon', models.CharField(blank=True, help_text='Emoji do kafelka na liście, np. 🤵', max_length=8)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('title_pl', models.CharField(help_text='Tytuł do zakładki przeglądarki i kafelka na liście.', max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('h1_pl', models.CharField(blank=True, help_text='Nagłówek H1 na stronie — puste = użyty tytuł powyżej.', max_length=200)),
                ('h1_en', models.CharField(blank=True, max_length=200)),
                ('excerpt_pl', models.CharField(blank=True, help_text='Krótki opis na kafelek listy /imprezy.', max_length=320)),
                ('excerpt_en', models.CharField(blank=True, max_length=320)),
                ('body_pl', models.TextField(blank=True, help_text='Treść strony (Markdown — nagłówki ## stają się H2).')),
                ('body_en', models.TextField(blank=True)),
                ('seo_title_pl', models.CharField(blank=True, max_length=160)),
                ('seo_title_en', models.CharField(blank=True, max_length=160)),
                ('seo_description_pl', models.CharField(blank=True, max_length=320)),
                ('seo_description_en', models.CharField(blank=True, max_length=320)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impreza / usługa okolicznościowa',
                'verbose_name_plural': 'Imprezy / usługi okolicznościowe',
                'ordering': ['order', 'title_pl'],
            },
        ),
        migrations.CreateModel(
            name='EventOfferPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='events/gallery/thumbs/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.eventoffer')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Galeria zdjęć',
                'ordering': ['order', 'id'],
            },
        ),
    ]
