# Generated by Django 5.2.16 on 2026-08-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_rename_event_offer_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoffer',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orientacyjna cena „od” (opcjonalnie), np. „od 400 zł” — dalej zawsze wycena indywidualna, to tylko punkt odniesienia. Puste = pokazujemy samo „Wycena indywidualna”, bez kwoty.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='eventoffer',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Pokazuj tę imprezę jako kafelek na stronie głównej (obok filaru „Imprezy okolicznościowe”).'),
        ),
        migrations.AddField(
            model_name='localroute',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena „od” pokazywana na kafelku i stronie trasy. Puste = wyliczana automatycznie z cennika odległościowego (jak dotychczas) — to pole NIE wpływa na cenę faktycznej rezerwacji, tylko na to, co widać na tej stronie.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='localroute',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Pokazuj na liście kierunków na stronie głównej. Wyłącz, żeby trasa była dostępna tylko pod swoim linkiem i na pełnej liście /kierunki, bez zajmowania miejsca na stronie głównej.'),
        ),
    ]
