# Generated by Django 5.2.16 on 2026-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_gsc_ctr_and_link_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20, unique=True)),
                ('phone', models.CharField(help_text='Format E.164, np. +48515020770 (używany w linkach tel: i WhatsApp).', max_length=20)),
                ('phone_display', models.CharField(help_text='Wersja do wyświetlenia, np. +48 515 020 770.', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('legal_name', models.CharField(blank=True, help_text='Pełna nazwa firmy w stopce/JSON-LD, np. "Michał Pielak MIKTEL".', max_length=160)),
                ('nip', models.CharField(blank=True, max_length=20)),
                ('address_street', models.CharField(blank=True, max_length=160)),
                ('address_postal_code', models.CharField(blank=True, max_length=10)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_country', models.CharField(default='PL', max_length=2)),
            ],
            options={
                'verbose_name': 'Dane kontaktowe',
                'verbose_name_plural': 'Dane kontaktowe',
            },
        ),
    ]
