# Generated by Django 5.2.16 on 2026-09-06 16:36

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_seed_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostlink',
            name='url',
            field=models.CharField(help_text='Pełny adres (https://...) dla linku zewnętrznego, albo ścieżka zaczynająca się od "/" dla linku wewnętrznego (np. "/" dla strony głównej, "/sledz" dla śledzenia kierowcy).', max_length=200, validators=[apps.content.models.validate_url_or_path]),
        ),
    ]
