# Generated by Django 5.2.16 on 2026-09-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_dowieziemycie_blog_rewrite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteShowcasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20)),
                ('category', models.CharField(choices=[('DRIVER', 'Kierowca'), ('VEHICLE', 'Samochód'), ('TRIP', 'Z wycieczek'), ('NEWS', 'Aktualności')], max_length=10)),
                ('image', models.ImageField(upload_to='showcase/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='showcase/thumbs/')),
                ('caption_pl', models.CharField(blank=True, max_length=160)),
                ('caption_en', models.CharField(blank=True, max_length=160)),
                ('caption_de', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Niższa wartość = wyżej/pierwsza w danej kategorii.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zdjęcie na stronę główną',
                'verbose_name_plural': 'Zdjęcia na stronę główną',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
