# Generated by Django 5.2.16 on 2026-09-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_revert_balice_guide_direction_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedroute',
            name='category',
            field=models.CharField(choices=[('LOTNISKO', 'Transfer lotniskowy'), ('TRANSFER', 'Transfer')], default='LOTNISKO', help_text='Decyduje pod jakim adresem trasa się pojawia: LOTNISKO -> /transfery-lotniskowe, TRANSFER -> /transfery (osobne strony, osobne adresy — celowo rozdzielone pod SEO).', max_length=20),
        ),
    ]
