# Generated by Django 5.2.16 on 2026-09-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_transfer247_fix_dworzec_energylandia_dead_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='page_type',
            field=models.CharField(choices=[('TRANSFER_LOTNISKO', 'Transfer lotniskowy'), ('NOCNY_TRANSFER', 'Nocny transfer'), ('LOKALNY_PRZEWOZ', 'Lokalny przewóz osób'), ('IMPREZY', 'Imprezy okolicznościowe'), ('WYNAJEM_DLUGIE_TRASY', 'Wynajem busa / długie trasy'), ('CENNIK', 'Cennik'), ('O_NAS', 'O nas'), ('KONTAKT', 'Kontakt'), ('BLOG', 'Wpis blogowy'), ('TRANSPORT_ROWEROW', 'Transport rowerów'), ('REGULAMIN', 'Regulamin'), ('INNE', 'Inne')], default='INNE', max_length=24),
        ),
    ]
