# Generated by Django 5.2.16 on 2026-09-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_seed_lokalny_przewoz_osob_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedroute',
            name='default_dropoff_label',
            field=models.CharField(blank=True, help_text='Tekst pokazywany klientowi w polu „Dokąd”. Puste = zostanie pobrany automatycznie ze znacznika.', max_length=200, verbose_name='Domyślny cel — adres'),
        ),
        migrations.AddField(
            model_name='fixedroute',
            name='default_dropoff_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Domyślny cel — szerokość'),
        ),
        migrations.AddField(
            model_name='fixedroute',
            name='default_dropoff_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Domyślny cel — długość'),
        ),
        migrations.AddField(
            model_name='fixedroute',
            name='default_pickup_label',
            field=models.CharField(blank=True, help_text='Tekst pokazywany klientowi w polu „Skąd”. Puste = zostanie pobrany automatycznie ze znacznika.', max_length=200, verbose_name='Domyślny start — adres'),
        ),
        migrations.AddField(
            model_name='fixedroute',
            name='default_pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Domyślny start — szerokość'),
        ),
        migrations.AddField(
            model_name='fixedroute',
            name='default_pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Domyślny start — długość'),
        ),
    ]
