# Generated by Django 5.2.16 on 2026-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0070_transfer247_vehicle_wording'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDriverPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20, unique=True)),
                ('day_hourly_rate', models.DecimalField(decimal_places=2, default=90, help_text='Stawka za godzinę pracy kierowcy w dzień (zł).', max_digits=6)),
                ('night_hourly_rate', models.DecimalField(decimal_places=2, default=120, help_text='Stawka za godzinę pracy kierowcy w nocy (zł) — wyższa, bo to praca po godzinach.', max_digits=6)),
                ('day_starts_at', models.TimeField(default='06:00', help_text='Od której godziny obowiązuje stawka dzienna.')),
                ('night_starts_at', models.TimeField(default='22:00', help_text='Od której godziny obowiązuje stawka nocna.')),
                ('price_per_100km', models.DecimalField(decimal_places=2, default=100, help_text='Cena za każde 100 km przejechane w trakcie wynajmu (dojazd, trasy między punktami imprezy).', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Odznacz, żeby ukryć tę sekcję na stronie bez usuwania ustawionych cen.')),
            ],
            options={
                'verbose_name': 'Cennik wynajmu kierowcy (imprezy)',
                'verbose_name_plural': 'Cennik wynajmu kierowcy (imprezy)',
            },
        ),
    ]
