# Generated by Django 5.2.16 on 2026-10-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_seed_event_driver_pricing'),
        ('fleet', '0012_protect_vehicle_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedroutevehicleprice',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_prices', to='fleet.vehicle'),
        ),
        migrations.AlterField(
            model_name='tourvehicleprice',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_prices', to='fleet.vehicle'),
        ),
    ]
