# Generated by Django 5.2.16 on 2026-10-08 15:42

import apps.content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_transfer247_restore_markdown_en_de_tours_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('item_type', models.CharField(choices=[('meble', 'Meble'), ('kartony', 'Kartony'), ('agd', 'AGD'), ('rowery', 'Rowery'), ('przeprowadzka', 'Przeprowadzka'), ('quad-motocykl', 'Quad / motocykl'), ('inne', 'Inne')], max_length=20)),
                ('description', models.TextField(max_length=3000)),
                ('vehicle_option', models.CharField(choices=[('bus', 'Bus'), ('trailer', 'Przyczepa'), ('unknown', 'Nie wiem')], default='unknown', max_length=10)),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('needs_carrying', models.BooleanField(default=False, help_text='Klient prosi o pomoc przy wnoszeniu.')),
                ('source_page', models.CharField(blank=True, max_length=140)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('locale', models.CharField(blank=True, max_length=5)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('wycenione', 'Wycenione'), ('zrealizowane', 'Zrealizowane'), ('odrzucone', 'Odrzucone')], default='nowe', max_length=12)),
                ('admin_notes', models.TextField(blank=True, help_text='Notatki wewnętrzne (wycena, ustalenia).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zapytanie o transport rzeczy',
                'verbose_name_plural': 'Zapytania o transport rzeczy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Kolejność podstron — mniejsze wyżej.')),
                ('is_published', models.BooleanField(default=False, help_text='Nieopublikowana strona zwraca 404 i nie trafia do menu ani sitemapy.')),
                ('noindex', models.BooleanField(default=False, help_text='Opublikowana, ale bez indeksowania w Google.')),
                ('menu_label_pl', models.CharField(blank=True, help_text='Krótka nazwa do menu i okruszków.', max_length=80)),
                ('menu_label_en', models.CharField(blank=True, max_length=80)),
                ('title_pl', models.CharField(help_text='Tytuł do kafelków i list.', max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('h1_pl', models.CharField(blank=True, help_text='Nagłówek H1 — puste = tytuł.', max_length=200)),
                ('h1_en', models.CharField(blank=True, max_length=200)),
                ('lead_pl', models.TextField(blank=True, help_text='2–3 zdania pod H1.')),
                ('lead_en', models.TextField(blank=True)),
                ('body_pl', models.TextField(blank=True, help_text='Treść strony (Markdown — nagłówki ## stają się H2).')),
                ('body_en', models.TextField(blank=True)),
                ('seo_title_pl', models.CharField(blank=True, max_length=160)),
                ('seo_title_en', models.CharField(blank=True, max_length=160)),
                ('seo_description_pl', models.CharField(blank=True, max_length=320)),
                ('seo_description_en', models.CharField(blank=True, max_length=320)),
                ('cover_image', models.ImageField(blank=True, help_text='Zdjęcie pod H1 i do udostępniania (Open Graph).', null=True, upload_to='services/covers/')),
                ('default_item_type', models.CharField(blank=True, choices=[('meble', 'Meble'), ('kartony', 'Kartony'), ('agd', 'AGD'), ('rowery', 'Rowery'), ('przeprowadzka', 'Przeprowadzka'), ('quad-motocykl', 'Quad / motocykl'), ('inne', 'Inne')], help_text='Co formularz zapytania ma zaznaczyć na starcie na tej stronie (np. przeprowadzka).', max_length=20)),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Kafelek w sekcji „Wybierz, co Cię interesuje” na stronie głównej.')),
                ('tile_icon', models.CharField(blank=True, help_text='Emoji kafelka, np. 📦', max_length=8)),
                ('tile_title_pl', models.CharField(blank=True, max_length=120)),
                ('tile_title_en', models.CharField(blank=True, max_length=120)),
                ('tile_body_pl', models.CharField(blank=True, help_text='Jedno zdanie na kafelek.', max_length=200)),
                ('tile_body_en', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Puste = strona kategorii (np. /transport-rzeczy). Ustawione = podstrona tej kategorii.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='content.servicepage')),
            ],
            options={
                'verbose_name': 'Strona usługi (transport rzeczy)',
                'verbose_name_plural': 'Strony usług (transport rzeczy)',
                'ordering': ['order', 'title_pl'],
            },
        ),
        migrations.CreateModel(
            name='ServicePagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='services/gallery/thumbs/')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('alt_pl', models.CharField(help_text='Opis zdjęcia dla niewidomych i Google — wymagany.', max_length=200)),
                ('alt_en', models.CharField(blank=True, max_length=200)),
                ('caption_pl', models.CharField(blank=True, max_length=200)),
                ('caption_en', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.servicepage')),
            ],
            options={
                'verbose_name': 'Zdjęcie realizacji',
                'verbose_name_plural': 'Galeria realizacji',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('bus', 'Bus'), ('trailer', 'Przyczepa')], max_length=20)),
                ('name_pl', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('description_pl', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Cena „od” w zł — puste = bez kwoty.', max_digits=7, null=True)),
                ('price_note_pl', models.CharField(blank=True, help_text='Np. „za kurs po Krakowie”.', max_length=160)),
                ('price_note_en', models.CharField(blank=True, max_length=160)),
                ('on_request', models.BooleanField(default=False, help_text='Zamiast ceny: „Na zapytanie — potwierdzamy termin”.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='content.servicepage')),
            ],
            options={
                'verbose_name': 'Opcja cenowa',
                'verbose_name_plural': 'Opcje cenowe',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransportInquiryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.content.models._inquiry_photo_path)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.transportinquiry')),
            ],
            options={
                'verbose_name': 'Zdjęcie do zapytania',
                'verbose_name_plural': 'Zdjęcia do zapytania',
            },
        ),
    ]
