# Generated by Django 5.2.16 on 2026-10-08 16:48

import datetime
from decimal import Decimal

from django.db import migrations, models


def seed_dowieziemycie(apps, schema_editor):
    # Starting values agreed with the owner (2026-10-08) — edited in Admin
    # from here on; never repeated in page texts (they use {rate:…} tokens).
    Pricing = apps.get_model("content", "GoodsTransportPricing")
    Pricing.objects.get_or_create(
        site="dowieziemycie",
        defaults={
            "hourly_rate": Decimal("80"),
            "night_hourly_rate": Decimal("100"),
            "day_starts_at": datetime.time(6, 0),
            "night_starts_at": datetime.time(22, 0),
            "price_per_100km": Decimal("100"),
            "trailer_price_per_day": Decimal("150"),
            "loading_price_from": None,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_service_pages_transport_inquiries'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTransportPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('dowieziemycie', 'dowieziemycie.pl'), ('transfer247', 'transfer247.pl')], default='dowieziemycie', max_length=20, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Token w tekstach: {rate:hour}', max_digits=7, verbose_name='Godzina pracy (dzień), zł')),
                ('night_hourly_rate', models.DecimalField(decimal_places=2, help_text='Token w tekstach: {rate:night}', max_digits=7, verbose_name='Godzina pracy (noc), zł')),
                ('day_starts_at', models.TimeField(verbose_name='Stawka dzienna od godziny')),
                ('night_starts_at', models.TimeField(verbose_name='Stawka nocna od godziny')),
                ('price_per_100km', models.DecimalField(decimal_places=2, help_text='Token w tekstach: {rate:100km}', max_digits=7, verbose_name='Każde 100 km trasy, zł')),
                ('trailer_price_per_day', models.DecimalField(decimal_places=2, help_text='Token: {rate:trailer}', max_digits=7, verbose_name='Przyczepa — dopłata za dobę, zł')),
                ('loading_price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Puste = „wycena indywidualna do zlecenia”. Token w tekstach: {rate:loading}', max_digits=7, null=True, verbose_name='Załadunek / rozładunek / wnoszenie — cena od, zł')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cennik transportu rzeczy',
                'verbose_name_plural': 'Cennik transportu rzeczy',
            },
        ),
        migrations.RunPython(seed_dowieziemycie, migrations.RunPython.noop),
    ]
