# Generated by Django 5.2.16 on 2026-07-27 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Np. Volkswagen T6', max_length=80)),
                ('plate', models.CharField(max_length=16, unique=True)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('seats', models.PositiveSmallIntegerField(default=7)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='vehicles/covers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('OFFLINE', 'Poza służbą'), ('DOSTEPNY', 'Aktywny (wolny)'), ('JADACY_PO_KLIENTA', 'W drodze do klienta'), ('W_KURSIE', 'W kursie'), ('WRACA_DO_BAZY', 'Wraca do bazy')], default='OFFLINE', max_length=20)),
                ('base_lat', models.DecimalField(decimal_places=6, default=50.0, max_digits=9)),
                ('base_lng', models.DecimalField(decimal_places=6, default=19.7, max_digits=9)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(help_text='Konto (staff-scoped) używane do logowania na stronie kierowcy.', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
