# Generated by Django 5.2.16 on 2026-07-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_seed_default_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['name'], 'verbose_name': 'Kierowca', 'verbose_name_plural': 'Kierowcy'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['name'], 'verbose_name': 'Pojazd', 'verbose_name_plural': 'Pojazdy'},
        ),
        migrations.AlterModelOptions(
            name='vehiclephoto',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Zdjęcie pojazdu', 'verbose_name_plural': 'Zdjęcia pojazdu'},
        ),
    ]
