# Generated by Django 5.2.16 on 2026-07-30 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_driver_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, help_text='Ten sam numer, którym kierowca loguje się przez SMS na /logowanie.', max_length=16, validators=[django.core.validators.RegexValidator(message='Podaj numer telefonu w formacie +48123456789 lub 123456789.', regex='^\\+?[0-9]{9,15}$')]),
        ),
    ]
