# Generated by Django 5.2.16 on 2026-07-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_driver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Ustawiane automatycznie przez aplikację mobilną kierowcy — używane do powiadomień push o nowych kursach.', max_length=200),
        ),
    ]
