# Generated by Django 5.2.16 on 2026-07-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_driver_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description_pl',
            field=models.TextField(blank=True, help_text='Opis marketingowy pokazywany na publicznej stronie floty.'),
        ),
    ]
