# Generated by Django 5.2.16 on 2026-07-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_seed_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_dispatcher',
            field=models.BooleanField(default=False, help_text='Widzi w aplikacji mobilnej kolejkę nowych rezerwacji do potwierdzenia (z możliwością zmiany ceny) i dostaje o nich powiadomienia push, niezależnie od własnego statusu.'),
        ),
    ]
