# Generated by Django 5.2.16 on 2026-08-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_driver_is_dispatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclephoto',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='vehicles/gallery/thumbs/'),
        ),
    ]
