# Generated by Django 5.2.16 on 2026-10-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_vehiclephoto_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description_transfer247_de',
            field=models.TextField(blank=True, verbose_name='opis na transfer247.pl (DE)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description_transfer247_en',
            field=models.TextField(blank=True, verbose_name='opis na transfer247.pl (EN)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description_transfer247_pl',
            field=models.TextField(blank=True, help_text='Puste = transfer247.pl pokazuje ogólny opis z pól powyżej.', verbose_name='opis na transfer247.pl (PL)'),
        ),
    ]
