# Generated by Django 5.2.16 on 2026-10-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_seed_vehicle_description_transfer247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclephoto',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='fleet.vehicle'),
        ),
    ]
