# Generated by Django 5.2.16 on 2026-07-27 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Podaj numer telefonu w formacie +48123456789 lub 123456789.', regex='^\\+?[0-9]{9,15}$')])),
                ('name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Podaj numer telefonu w formacie +48123456789 lub 123456789.', regex='^\\+?[0-9]{9,15}$')])),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'code'], name='accounts_ph_phone_373c3c_idx')],
            },
        ),
    ]
