# Generated by Django 5.2.16 on 2026-07-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Klient', 'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='phoneotp',
            options={'verbose_name': 'Kod SMS', 'verbose_name_plural': 'Kody SMS'},
        ),
    ]
