# Generated by Django 5.2.16 on 2026-07-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_alter_phoneotp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Opcjonalny — jeśli podany, dostaje też powiadomienia e-mail.', max_length=254),
        ),
    ]
