# Generated by Django 5.2.16 on 2026-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_code',
            field=models.CharField(blank=True, help_text='Stały kod klienta ustawiany po potwierdzeniu SMS-em. Służy do kolejnych logowań.', max_length=6),
        ),
    ]
